In [1]:
import pandas as pd
import numpy as np
import datetime
import talib as ta
import mplfinance as mpf
import matplotlib.pyplot as plt
from iexfinance.stocks import get_historical_data

In [2]:
# 解决matplotlib无法显示中文的问题
plt.rcParams['font.family'] = ['sans-serif']
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
%matplotlib inline

In [3]:
start_date = datetime.date(2021,1,1)
api_key = 'sk_6da55e0040724dae968ee05db3cb1974'
df = get_historical_data('MSFT',output_format='pandas',token=api_key, start=start_date)
df.head()

close      high       low    open symbol    volume  \
2021-01-04  217.69       223    214.81  222.53   MSFT  37130139   
2021-01-05   217.9    218.52     215.7  217.26   MSFT  23822953   
2021-01-06  212.25  216.4899    211.94  212.17   MSFT  35930653   
2021-01-07  218.29    219.34    213.71  214.04   MSFT  27694480   
2021-01-08  219.62    220.58  217.0261  218.68   MSFT  22956206   

                           id   key subkey        updated  ...      uLow  \
2021-01-04  HISTORICAL_PRICES  MSFT         1653420604000  ...    214.81   
2021-01-05  HISTORICAL_PRICES  MSFT         1653420249000  ...     215.7   
2021-01-06  HISTORICAL_PRICES  MSFT         1653420401000  ...    211.94   
2021-01-07  HISTORICAL_PRICES  MSFT         1653420249000  ...    213.71   
2021-01-08  HISTORICAL_PRICES  MSFT         1653420556000  ...  217.0261   

             uVolume     fOpen    fClose     fHigh      fLow   fVolume  \
2021-01-04  37130139  219.7131  214.9344  220.1772  212.0908  37130139   
2021-01-05  23822953  214.5098  215.1417  215.7539  212.9696  23822953   
2021-01-06  35930653  209.4842  209.5632  213.7495  209.2572  35930653   
2021-01-07  27694480  211.3306  215.5268  216.5635  211.0048  27694480   
2021-01-08  22956206  215.9118  216.8399  217.7878  214.2789  22956206   

                label change changePercent  
2021-01-04  Jan 4, 21  -4.73       -0.0213  
2021-01-05  Jan 5, 21   0.21         0.001  
2021-01-06  Jan 6, 21  -5.65       -0.0259  
2021-01-07  Jan 7, 21   6.04        0.0285  
2021-01-08  Jan 8, 21   1.33        0.0061  

[5 rows x 25 columns]

In [4]:
# Now we need to get open, close, high, low price seperately
open_price = np.array(df['open'],dtype='f8')
close_price = np.array(df['close'],dtype='f8')
high_price = np.array(df['high'],dtype='f8')
low_price = np.array(df['low'],dtype='f8')
print(low_price)

[214.81   215.7    211.94   213.71   217.0261 216.73   213.3202 213.9266
 212.74   212.03   212.63   217.2908 222.42   225.8    224.22   230.08
 230.14   235.09   231.35   232.43   238.69   239.26   240.37   240.42
 240.81   241.38   240.89   242.15   242.73   242.92   240.94   240.86
 240.18   232.4    228.73   229.     227.88   229.54   233.15   233.45
 227.26   224.26   226.46   227.13   231.67   232.04   234.31   233.23
 231.81   235.94   233.23   230.33   229.3496 230.14   237.07   235.32
 231.57   231.55   231.88   231.1    232.39   238.0501 242.7    246.88
 247.19   252.     252.44   254.62   256.83   255.16   257.73   257.6014
 257.821  256.84   257.25   255.64   257.27   260.17   260.12   252.95
 249.     249.6    251.12   245.76   245.82   244.69   251.17   247.12
 242.57   238.07   241.42   245.49   243.52   242.9    238.6    243.86
 244.74   247.51   250.82   250.75   249.25   249.56   246.96   245.84
 243.     247.51   249.81   252.51   253.21   253.67   256.61   256.8
 25

In [5]:
# 早晨之星 Morning Star 符合条件的标记为100 不符合条件的标记为0
ms = ta.CDLMORNINGSTAR(open_price, high_price, low_price, close_price)
# 打印非零的值
print(ms[ms!=0])
ms[:100]

[]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
signal = np.where(ms==100,close_price,np.nan)
signal[:100]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [7]:
if len(ms[ms!=0]) > 0:
    add_plot = mpf.make_addplot(signal, type='scatter', markersize=100, marker='^', color='b', secondary_y=False)
    # 作图
    mpf.plot(df,type='candle',addplot=add_plot, style=s, figsize=(16,10))
else:
    print('所选的行情中没有出现早晨之星')

所选的行情中没有出现早晨之星


## 三只乌鸦

In [8]:
three_crows = ta.CDL3BLACKCROWS(open_price, high_price, low_price, close_price)
three_crows[three_crows!=0]

array([], dtype=int32)

## RSI

In [11]:
#rsi_result = ta.momentum.RSIIndicator(close_price,14).rsi()
ta.RSI(close_price,14)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 64.83709273,
       67.30776125, 67.80371027, 72.54820776, 61.30302651, 67.32142719,
       67.11677258, 69.59792544, 68.02982848, 68.17801442, 68.40215184,
       69.51549863, 67.63989604, 69.21247172, 69.68743771, 66.82313494,
       67.38273398, 66.39379916, 59.88383522, 48.21989217, 46.35354436,
       48.56656197, 40.71057768, 46.403192  , 52.94754423, 48.64136857,
       41.22078812, 40.34882837, 47.38198313, 42.69546053, 50.67073396,
       49.10434641, 54.3657284 , 52.64842364, 51.4561045 , 54.85306316,
       53.91437423, 45.92994785, 45.50506595, 52.68949017, 54.51024769,
       51.65570715, 47.69700702, 52.85949395, 51.22850822, 46.96232553,
       51.94577823, 58.92281554, 64.57905406, 62.89957144, 64.57241329,
       67.18877468, 69.09633952, 69.14092591, 71.07352206, 66.06